server:
  port: 8081
keycloak:
  auth-server-url: http://localhost:8080
  realm: Spring
  resource: login-app
  public-client: true
  principal-attribute: preferred_username
spring:
  main:
    allow-circular-references: true